# ⚙️ Student Performance AI

# Notebook 03 — Data Preprocessing

## Objective

Raw datasets cannot be directly used for training neural networks.

In this notebook, we will prepare the dataset for model training by:

- Loading the dataset
- Separating features and target
- Encoding categorical variables
- Scaling numerical variables
- Splitting into training and testing sets
- Converting the data into PyTorch tensors

This notebook creates the final dataset that will be used for model training.

In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [3]:
DATA_PATH = "../data/raw/student-performance.csv"
df  = pd.read_csv(DATA_PATH, sep=";")
df.head()
print("Data Loaded Successfully")

Data Loaded Successfully

# Separate Features and Target

In [4]:
X = df.drop("G3", axis=1)

y = df["G3"]

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (649, 32)
Target Shape : (649,)

In [5]:
categorical_features = X.select_dtypes(include="object").columns.tolist()

numerical_features = X.select_dtypes(exclude="object").columns.tolist()

print("Categorical:", len(categorical_features))
print("Numerical:", len(numerical_features))

Categorical: 17
Numerical: 15

# One-Hot Encoding

Neural networks cannot process text values.

Therefore categorical variables must be converted into numerical vectors.

In [6]:
encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

encoded = encoder.fit_transform(
    X[categorical_features]
)

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(categorical_features)
)

encoded_df.head()

,school_GP,school_MS,sex_F,sex_M,address_R,address_U,famsize_GT3,famsize_LE3,Pstatus_A,Pstatus_T,...,activities_no,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes
0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
3,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

In [7]:
numerical_df = X[numerical_features].reset_index(drop=True)

X_processed = pd.concat(
    [numerical_df, encoded_df],
    axis=1
)

X_processed.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,activities_no,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,17,1,1,1,2,0,5,3,3,1,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,15,1,1,1,2,0,4,3,2,2,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
3,15,4,2,1,3,0,3,2,2,1,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
4,16,3,3,1,2,0,4,3,2,1,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

# Feature Scaling

Neural networks train faster when numerical features are standardized.

In [8]:
scaler = StandardScaler()

X_processed[numerical_features] = scaler.fit_transform(
    X_processed[numerical_features]
)

X_processed.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,activities_no,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes
0,1.031695,1.310216,1.540715,0.576718,0.083653,-0.374305,0.072606,-0.171647,0.693785,-0.543555,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.210137,-1.336039,-1.188832,-0.760032,0.083653,-0.374305,1.119748,-0.171647,-0.157380,-0.543555,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,-1.432980,-1.336039,-1.188832,-0.760032,0.083653,-0.374305,0.072606,-0.171647,-1.008546,0.538553,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
3,-1.432980,1.310216,-0.278983,-0.760032,1.290114,-0.374305,-0.974536,-1.123771,-1.008546,-0.543555,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
4,-0.611422,0.428131,0.630866,-0.760032,0.083653,-0.374305,0.072606,-0.171647,-1.008546,-0.543555,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X_processed,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Samples :", X_train.shape)

print("Testing Samples :", X_test.shape)

Training Samples : (519, 58)
Testing Samples : (130, 58)

In [10]:
import torch

X_train_tensor = torch.tensor(
    X_train.values,
    dtype=torch.float32
)

X_test_tensor = torch.tensor(
    X_test.values,
    dtype=torch.float32
)

y_train_tensor = torch.tensor(
    y_train.values,
    dtype=torch.float32
).view(-1,1)

y_test_tensor = torch.tensor(
    y_test.values,
    dtype=torch.float32
).view(-1,1)

print(X_train_tensor.shape)

print(y_train_tensor.shape)

torch.Size([519, 58])
torch.Size([519, 1])

In [11]:
print("Feature Count:", X_train_tensor.shape[1])

print("Target Shape:", y_train_tensor.shape)

Feature Count: 58
Target Shape: torch.Size([519, 1])

# Summary

The dataset has now been successfully prepared for neural network training.

Completed:

- Loaded Dataset
- Split Features and Target
- Encoded Categorical Variables
- Scaled Numerical Variables
- Created Train/Test Split
- Converted Data to PyTorch Tensors

The processed tensors are now ready for creating PyTorch Dataset and DataLoader objects.

# Next Notebook

Notebook 04

PyTorch Dataset & DataLoader

We will create:

- Custom Dataset
- DataLoader
- Batch Processing
- Efficient Data Pipeline